source 'https://github.com/CocoaPods/Specs.git'

target 'CLPVerticalButton', :exclusive => true do
  pod "CLPVerticalButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CLPVerticalButton", :path => "../"

  
end
